### PR TITLE
Adds ASN.1 BER Unmarshalling

### PR DESCRIPTION
**Pull request by geoffgarside**
While using this package I found some SNMP devices returning BER rather then DER ASN.1 encoded packets. The SNMP RFC itself defines BER as the ASN.1 encoding standard to be used, DER is technically a sub-set so DER is valid BER, but not the other way around. Because of this the golang `encoding/asn1` package, which is DER compliant, will fail to parse some valid BER content.

These commits copy the unmarshalling sections of the golang `encoding/asn1` package and uses asn1 types and functions where they're exported. Changes are made to relax some of the data checks imposed to validate DER requirements so the BER is accepted.

Tests are included for the `ber` package (copied from `encoding/asn1` and modified as required) as well as some new tests for `snmpgo` to ensure the BER encoded SNMP packets are unmarshalled correctly.

### CODE REVIEW

**Comment by geoffgarside** [comment]
Checks have failed on Golang 1.5, looks like the `encoding/asn1` package was enhanced with some additional variables and string support in Golang 1.6. Whats the policy on supporting older versions of Golang? I'll see what I can do about handling these missing types though.

**Comment by geoffgarside** [comment]
Appears golang 1.5 -> 1.6 exported all of the tag* and class* variables. I've copied these across now, they're defined explicitly for golang 1.5, while I don't expect them to change in future I've opted to set the interval values to the exported asn1 values just in case.

**Comment by k-sone** [comment]
I'm so sorry for not replying sooner.

> The SNMP RFC itself defines BER as the ASN.1 encoding standard to be used, DER is technically a sub-set so DER is valid BER, but not the other way around.

I agree with you.

> These commits copy the unmarshalling sections of the golang encoding/asn1 package and uses asn1 types and functions where they're exported.

I hope to manage the `ber` package as a separate repository from the `snmpgo`. Because I don't want to include different licenses in one repository.
Would it be possible to create the `ber` package as your repository?

**Comment by k-sone** [comment]
> Whats the policy on supporting older versions of Golang?

I would like to support up to three new versions including the latest version. But I am still using Go1.5 😣

**Comment by geoffgarside** [comment]
Yeah I can move the `ber` package to my account, I'll get the PR updated with the new import path.

**Comment by geoffgarside** [comment]
Ok, I've moved `ber` and got Travis setup, I've copied your `.travis.yml` file (added go1.8) so the runtime support should be the same.

I've added you as a collaborator on the repo so it being separate shouldn't hinder fixing or improving things in the future hopefully.

**Comment by k-sone** [comment]
Thank you very much.

I have one additional request. Could you cancel or revert 7fad1e62d6a8bb59bc529f14abf01d1bcb66583a commit?

**Comment by geoffgarside** [comment]
Certainly :)

I tend to use `gb` to keep development areas isolated and the `gb build` command was complaining as there are multiple `main` functions in that directory.

**Comment by k-sone** [comment]
Looks good to me. But I will check this in my environment.
Please wait for a few days.

**Comment by k-sone** [comment]
Thanks for your contribution!

I also found an SNMP device(firewall of a certain manufacturer) with the same problem and confirmed that it was fixed.
This PR gave me a much better understanding of the ASN.1 and SNMP.

**Comment by geoffgarside** [comment]
Yeah me too, probably learnt more about ASN.1 and SNMP than I really wanted to know :)

**Pull request merged**
